"""Train the XGBoost risk-scoring model on a synthetic labeled dataset.

Generates a synthetic labeled transaction dataset with the same
hand-crafted, semantically-meaningful generator used by the real-time
producer (app/generator.py) -- so the offline training distribution matches
what the online scorer will see -- transforms it with the exact same
feature pipeline the consumer uses (app/features.py), trains a gradient
boosted tree classifier, evaluates it on a held-out split, and saves:

  * training/model.pkl     -- joblib bundle: {model, feature_names, model_version}
  * training/metrics.json  -- precision / recall / AUC / etc measured on the
                               held-out split of *this run's* synthetic data

These are real numbers measured against synthetic data generated by this
repo, not production traffic -- see the README for that framing.

Run:
    .venv/bin/python -m training.train_model
"""
from __future__ import annotations

import argparse
import json
import random
import time
from pathlib import Path

import joblib
import numpy as np
from sklearn.metrics import (
    average_precision_score,
    precision_recall_fscore_support,
    roc_auc_score,
)
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier

from app.features import FEATURE_NAMES, transform_batch
from app.generator import generate_customer_pool, generate_transaction

THIS_DIR = Path(__file__).resolve().parent
MODEL_PATH = THIS_DIR / "model.pkl"
METRICS_PATH = THIS_DIR / "metrics.json"

MODEL_VERSION = "1.0.0"


def build_dataset(
    n_samples: int,
    fraud_rate: float,
    n_customers: int,
    seed: int,
) -> tuple[np.ndarray, np.ndarray]:
    """Generate n_samples synthetic (feature_vector, label) pairs."""
    rng = random.Random(seed)
    customers = generate_customer_pool(n_customers, rng)

    raws = []
    labels = np.empty(n_samples, dtype=np.int64)
    for i in range(n_samples):
        raw, label = generate_transaction(rng, customers, fraud_rate=fraud_rate)
        raws.append(raw)
        labels[i] = label

    X = transform_batch(raws)
    return X, labels


def train(
    n_samples: int = 60_000,
    fraud_rate: float = 0.03,
    n_customers: int = 500,
    seed: int = 42,
    test_size: float = 0.2,
) -> dict:
    print(f"Generating {n_samples} synthetic transactions (fraud_rate={fraud_rate})...")
    X, y = build_dataset(n_samples, fraud_rate, n_customers, seed)
    print(f"Dataset shape: {X.shape}, positive rate: {y.mean():.4f}")

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=test_size, random_state=seed, stratify=y
    )

    # scale_pos_weight compensates for the class imbalance inherent to fraud
    # detection (fraud is rare by construction, same as in the real world).
    n_pos = max(int(y_train.sum()), 1)
    n_neg = len(y_train) - n_pos
    scale_pos_weight = n_neg / n_pos

    model = XGBClassifier(
        n_estimators=200,
        max_depth=5,
        learning_rate=0.08,
        subsample=0.9,
        colsample_bytree=0.9,
        scale_pos_weight=scale_pos_weight,
        eval_metric="aucpr",
        random_state=seed,
        n_jobs=-1,
    )

    print("Training XGBoost classifier...")
    start = time.perf_counter()
    model.fit(X_train, y_train)
    train_seconds = time.perf_counter() - start
    print(f"Training completed in {train_seconds:.2f}s")

    y_proba = model.predict_proba(X_test)[:, 1]
    y_pred = (y_proba >= 0.5).astype(int)

    precision, recall, f1, _ = precision_recall_fscore_support(
        y_test, y_pred, average="binary", zero_division=0
    )
    auc_roc = roc_auc_score(y_test, y_proba)
    auc_pr = average_precision_score(y_test, y_proba)

    metrics = {
        "model_version": MODEL_VERSION,
        "trained_at_unix": time.time(),
        "n_samples": n_samples,
        "n_train": int(len(X_train)),
        "n_test": int(len(X_test)),
        "fraud_rate_synthetic": fraud_rate,
        "test_positive_rate": float(y_test.mean()),
        "precision": float(precision),
        "recall": float(recall),
        "f1": float(f1),
        "roc_auc": float(auc_roc),
        "pr_auc": float(auc_pr),
        "train_seconds": train_seconds,
        "note": (
            "All metrics measured on a held-out split of synthetic data generated "
            "by app/generator.py in this repo. Not production traffic."
        ),
    }

    print(json.dumps(metrics, indent=2))

    MODEL_PATH.parent.mkdir(parents=True, exist_ok=True)
    joblib.dump(
        {
            "model": model,
            "feature_names": FEATURE_NAMES,
            "model_version": MODEL_VERSION,
        },
        MODEL_PATH,
    )
    print(f"Saved model to {MODEL_PATH}")

    with open(METRICS_PATH, "w") as f:
        json.dump(metrics, f, indent=2)
    print(f"Saved metrics to {METRICS_PATH}")

    return metrics


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train the synthetic risk-scoring model")
    parser.add_argument("--n-samples", type=int, default=60_000)
    parser.add_argument("--fraud-rate", type=float, default=0.03)
    parser.add_argument("--n-customers", type=int, default=500)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--test-size", type=float, default=0.2)
    return parser.parse_args(argv)


def main() -> None:
    args = parse_args()
    train(
        n_samples=args.n_samples,
        fraud_rate=args.fraud_rate,
        n_customers=args.n_customers,
        seed=args.seed,
        test_size=args.test_size,
    )


if __name__ == "__main__":
    main()
